# @package _global_

defaults:
  - /benchmark: findingdory_multitask
  - /habitat/simulator/sim_sensors@habitat_baselines.eval.extra_sim_sensors.third_rgb_sensor: third_rgb_sensor
  - _self_


habitat_baselines:
  video_dir: "data/findingdory_outputs/qwen35_mapper/video"

  agent:
    _target_: findingdory.policies.heuristic.vlm_mapper.VLMMapperAgent
    config:
      model: "Qwen/Qwen3.5-4B"
      model_loader: "auto_image_text"
      enable_thinking: False
      max_new_tokens: 512
      prompt_file: "findingdory/policies/llm/prompts/qwen_prompt.txt"
      chunk_size: 250
      subsample_frames: True
      vlm_temp_folder: "data/findingdory_outputs/qwen35_mapper/temp"
      output_folder: "data/findingdory_outputs/qwen35_mapper/logs"
      pointnav_max_steps: 1000
      turn_angle: 10
      delay_between_tasks: 0

  additional_success_metrics:
    vlm_subgoal_metrics:
      - high_level_goal_success
      - high_level_dtg_success
      - high_level_sem_cov_success
